name: Publish Logs Image
on:
  push:
    paths:
    - 'logs/Dockerfile.logs'
   
jobs:
  buildAndPush:
    name: "Webhook - Build And Push docker images"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Logs
        id: docker_build_logs
        uses: docker/build-push-action@v2
        with:
          context: logs
          file: logs/Dockerfile.logs
          push: true
          tags: ghcr.io/terranblake/logs:latest
      - name: logs Image digest
        run: echo logs ${{ steps.docker_build_logs.outputs.digest }}
      - name: Trigger deployer
        run: |
          payload='{ "application_name": "logs", "image_digest": "${{ steps.docker_build.outputs.digest }}", "image_tag": "latest" }'
          token='X-Webhook-Token: ${{ secrets.WEBHOOK_SECRET }}'
          curl -i -X POST -H 'Content-Type: application/json' -H "${token}"  -d "${payload}" https://hooks.terranblake.com/hooks/deploy
